aws:
  dynamodb:
    endpoint: http://localhost:4566
    region: us-east-1

step-functions:
  state-machine-arn: arn:aws:states:us-east-1:000000000000:stateMachine:card-transaction-system-transaction-saga

logging:
  level:
    root: INFO
    com.empresa.cardtransactionsystem: DEBUG
    software.amazon.awssdk: WARN

management:
  otlp:
    metrics:
      export:
        step: 10s
