{
 "title": "Temporal Saga Monitoring",
 "tags": [
  "temporal",
  "saga",
  "payments"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Temporal Activities Throughput (TPS)",
   "type": "row",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Throughput por Atividade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(temporal_activity_validate_seconds_count[1m]))",
     "legendFormat": "Validate Rules"
    },
    {
     "expr": "sum(rate(temporal_activity_fraud_seconds_count[1m]))",
     "legendFormat": "Analyze Fraud"
    },
    {
     "expr": "sum(rate(temporal_activity_status_seconds_count[1m]))",
     "legendFormat": "Update Status"
    }
   ]
  },
  { "title": "Latency (Seconds)", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Latência Média",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(temporal_activity_validate_seconds_sum[1m]) / rate(temporal_activity_validate_seconds_count[1m])",
     "legendFormat": "Validate (Avg)"
    },
    {
     "expr": "rate(temporal_activity_fraud_seconds_sum[1m]) / rate(temporal_activity_fraud_seconds_count[1m])",
     "legendFormat": "Fraud (Avg)"
    }
   ]
  },
  {
   "title": "Picos de Latência (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "temporal_activity_validate_seconds_max",
     "legendFormat": "Validate (Max)"
    },
    {
     "expr": "temporal_activity_fraud_seconds_max",
     "legendFormat": "Fraud (Max)"
    }
   ]
  },
  { "title": "Reliability & Errors", "type": "row", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Taxa de Erro Antifraude",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(temporal_activity_fraud_seconds_count{error!=\"none\"}[5m])) / sum(rate(temporal_activity_fraud_seconds_count[5m])) * 100",
     "legendFormat": "Fraud Error Rate"
    }
   ]
  },
  {
   "title": "Exceções Detalhadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (error) (rate(temporal_activity_validate_seconds_count{error!=\"none\"}[5m]))",
     "legendFormat": "Validate Exceptions: {{error}}"
    },
    {
     "expr": "sum by (error) (rate(temporal_activity_fraud_seconds_count{error!=\"none\"}[5m]))",
     "legendFormat": "Fraud Exceptions: {{error}}"
    }
   ]
  }
 ]
}